### ISSUE TITLE
Shiny Gadgets in RStudio Server?

### ISSUE THREAD

**Issue by olyerickson** [rstudio/miniUI#9]
My default, Shiny Gadgets want to listen on `http://127.0.0.1:6976`, but that doesn't work for RStudio Server, which should listen on whatever is appropriate for that server. 

I've tested a number of gadgets (and add-ins that use gadgets as UIs) and they "sort of" work, but are grayed out and the reactiveness is broken. 

What is the solution to Shiny Gadgets on RStudio Server?

**Comment by jjallaire** [comment]
RStudio Server implements port proxying for this scenario. The form of the proxy URLs is (e.g. for server "myserver.com"):

```
http://myserver.com/p/6976/
```

When running under RStudio Server calls to `browseURL` which use URLs of the form "http://127.0.0.1:6976" are automatically mapped to the form `/p/6976`.

So the net is that that Gadgets (and Shiny applications run via `runApp`) should "just work" on RStudio Server. It may be that you are invoking or browsing to your gadget in some way we don't expect in which case your mileage would vary.

**Comment by olyerickson** [comment]
Thanks for your quick response!

I see this problem even for your `tabs.R` example. When I execute it I see:
![selection_077](https://cloud.githubusercontent.com/assets/358649/23866974/cfa869a6-07f0-11e7-9f89-7bbc0331530e.png)

Is it possible we have something configured wrong with our RStudio Server installation?

**Comment by jjallaire** [comment]
My guess is that there is a proxy somewhere in between your browser and the
RStudio Server that is not handling websockets traffic correctly. Here is a
our support article on running with a proxy (example code for Nginx and
Apache reverse proxies is provided):
https://support.rstudio.com/hc/en-us/articles/200552326-Running-RStudio-Server-with-a-Proxy

**Comment by olyerickson** [comment]
Problem solved; thanks for the pointers! It was indeed an issue with our proxy server.

**Comment by anirudhchoudary** [comment]
Hi olyerickson

We are running into a similar issue that you represented in your screenshots. I've tried the confiugurations mentioned in the rstudio article above, but the issue persisted. Could you please provide any information on the steps or configurations you carried out to fix this issue in proxy server?
